---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
        files: ^questionary/
      - id: mixed-line-ending
        files: ^questionary/
      - id: trailing-whitespace
        files: ^questionary/

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
      - id: pyupgrade
        files: ^questionary/
        args: [--py38-plus]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.0
    hooks:
      - id: add-trailing-comma
        files: ^questionary/

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        files: ^questionary/
        args: [ --add-import, "from __future__ import annotations" ]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
    hooks:
      - id: pycln
        files: ^questionary/
        args: [ --all ]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations
        files: ^questionary/
      - id: python-check-blanket-noqa
        files: ^questionary/

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        files: ^questionary/

  - repo: https://github.com/PyCQA/flake8.git
    rev: '3.8.3'
    hooks:
      - id: flake8
        files: ^questionary/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        files: ^questionary/

  - repo: https://github.com/python-poetry/poetry
    rev: "1.2.2"
    hooks:
      - id: poetry-check
